using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace xlperimental_mod
{
    public static class Patreons
    {
        public static string[] names = new string[]
           {
            "doobiedoober",
            "Eric Mcgrady",
            "Slabs",
            "Marcel Mink",
            "helio",
            "Kyle Gherman",
            "Max Crowe",
            "Nick Morocco",
            "Nick Hanslip",
            "Bubble Gun",
            "Matt B",
            "Justin Lamothe",
            "Euan",
            "J'vonte Johnson",
            "Foolie Surfin",
            "Alex Tagg",
            "Jeffery Depriest",
            "Nati Adams",
            "dustin fuston",
            "Dali",
            "Ardell Manning",
            "V I E",
            "Nathaniel Gardner",
            "Corey Populus",
            "countinsequence",
            "Roko Kvesic",
            "nahkel skylar",
            "Justin S Reynolds",
            "Ross Hill",
            "Joel de Roll",
            "Seth Bates",
            "etown sk8r",
            "Alex Baker",
            "JMCAutomatic",
            "Christian Joel",
            "Zaheer",
            "Mink",
            "kevin hardy",
            "Seriel TK",
            "Matthew Kucinski",
            "renzoh",
            "Pat Dunn",
            "kevin4mayor",
            "Drippy QTip",
            "Malcolm hazley",
            "jacquez l brown",
            "fleep",
            "Noa Decker",
            "t",
            "Cruzzy",
            "ClutchClubz YT",
            "Aaron ward",
            "alex",
            "Gabriel Rosa",
            "Bob Gnarly",
            "alexandro garcia",
            "Babyfacedbull",
            "Austin Birch",
            "Jake Caruncho",
            "Self destruct",
            "Mathew Boynton",
            "Jayden",
            "James Healy",
            "Predstava Procezz",
            "Matthew James",
            "Sean Davis",
            "Mitchell",
            "Jordan Byrd",
            "Lochie Axon",
            "Jake Roush",
            "Chris Espinal",
            "Benny Nixx",
            "Mr Karl Havelock",
            "jesper lindkvist",
            "Robert White",
            "thomas medina",
            "Michael Cusumano",
            "Braxton Hardison",
            "Austin Quick",
            "Theo Sundqvist",
            "BoardDistribution AuthorityDownMahagoniEtaksSticky",
            "Austen",
            "Marcy Eris",
            "totally _monke",
            "Die Trying Crew AlwaysRiding",
            "Leslie Frank Albert"
           };
    }
}
